server:
  port: 9100
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud01_order?useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        # 集群
        cluster-name: XA
        # 命名空间
        namespace: test
        # 是否是临时实例，临时实例（数据可靠性要求低）：心跳检测且剔除；非临时实例：主动检测，不剔除
        ephemeral: true
        # 业务分组
        # group: order
    sentinel:
      transport:
        dashboard: localhost:8080
      # 关闭 Context 整合
      web-context-unify: false
      datasource:
        flow:
          nacos:
            # Nacos 地址
            server-addr: localhost:8848
            # 配置文件名称
            data-id: order-service-flow-rules
            group-id: SENTINEL_GROUP
            # 规则类型：degrade authority param-flow
            rule-type: flow
        degrade:
          nacos:
            # Nacos 地址
            server-addr: localhost:8848
            # 配置文件名称
            data-id: order-service-degrade-rules
            group-id: SENTINEL_GROUP
            # 规则类型：degrade authority param-flow
            rule-type: degrade

### mybatis-plus 配置
mybatis-plus:
  type-aliases-package: com.github.stazxr.study.cloud1.service.order.entity
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

### 输出日志
logging:
  file:
    path: /home/cloud1/${spring.application.name}/logs/services

### eureka 配置
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#    # prefer-ip-address: true
#    # home-page-url-path: ${server.servlet.context-path}
#    # lease-renewal-interval-in-seconds: 5
#    # lease-expiration-duration-in-seconds: 15
#  client:
#    # fetch-registry: true
#    # registry-fetch-interval-seconds: 15
#    # register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/

### feign 配置
feign:
  client:
    config:
      ### 全局生效
      default:
        ### 日志级别 NONE,BASIC,HEADERS,FULL;
        logger-level: BASIC
      ### 局部生效
      # user-service:
        # logger-level: BASIC
  httpclient:
    # 开启 feign 对 httpclient 的支持
    enabled: true
    # 最大的链接数
    max-connections: 200
    # 每个路径的最大链接数
    max-connections-per-route: 50
  sentinel:
    # 开启 feign 对 sentinel 的支持
    enabled: true
