server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  server:
    # 是否开启保护模式：保护模式下 Eureka Server 将会尝试保护其服务注册表中的信息，不再删除服务注册表中的数据，也就是不会注销任何微服务。
    enable-self-preservation: false
  instance:
    hostname: ${EUREKA_HOSTNAME:${spring.cloud.client.ip-address}}
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    # 同台机器部署多实例，需要为 false，并且 defaultZone 中不能用 IP 地址方式，要配置 hosts 后用 hostname 方式
    # 否则会出现界面 unavailable-replicas 的问题，原因是注册的集群注册优先使用 IP，而 IP 都一样导致的。如果为 false 默认使用 hostname。
    prefer-ip-address: false
  client:
    # Eureka 是否也注册到 Eureka 中
    register-with-eureka: ${EUREKA_REGISTER:true}
    # 是否从 Eureka Server获取注册信息
    fetch-registry: ${EUREKA_FETCH:true}
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://127.0.0.1:${server.port}/eureka/}
      # defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/