server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud01_user?useSSL=false
    username: root
    password: root
mybatis-plus:
  type-aliases-package: com.github.stazxr.study.cloud1.service.user.entity
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    path: /home/cloud1/${spring.application.name}/logs/services
debug: false
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    # prefer-ip-address: true
    # home-page-url-path: ${server.servlet.context-path}
    # lease-renewal-interval-in-seconds: 5
    # lease-expiration-duration-in-seconds: 15
  client:
    # fetch-registry: true
    # registry-fetch-interval-seconds: 15
    # register-with-eureka: true
    serviceUrl:
      # defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/